# easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User


easy_admin:
    entities:
      Product:
        class: "App\\Entity\\Product"
        list:
          fields:
            - label
            - description
            - price
            - updatedAt
            - { property: 'imageName', type: 'image', base_path: '/images/products', label: 'Image'}
        show:
          fields:
            - { property: 'imageName', type: 'image', base_path: '/images/products'}
        form:
          fields:
            - label
            - description
            - { property: 'price', type: 'money', type_options: { divisor: 100 }}
            - { property: 'imageFile', type: 'vich_image'}